# 基础配置
base:
  log_level: INFO
  data_source: "akshare"

# 策略配置
strategy:
  indicators:
    ma_cross:
      weight: 0.12
      params:
        short_window: 5
        long_window: 20
    bollinger:
      weight: 0.12
      params:
        window: 20
        std_dev: 2
    rsi:
      weight: 0.08
      params:
        window: 14
    macd:
      weight: 0.12
      params:
        fast: 12
        slow: 26
        signal: 9
    kdj:
      weight: 0.08
      params:
        window: 9
    volume:
      weight: 0.12
    dmi:
      weight: 0.08
      params:
        window: 14
    cci:
      weight: 0.05
      params:
        window: 20
    trix:
      weight: 0.05
      params:
        window: 12
    obv:
      weight: 0.06
    wr:
      weight: 0.06
      params:
        window: 14
    emv:
      weight: 0.06

# 风险控制
risk:
  stop_loss: 0.07
  take_profit: 0.15
  max_position_per_stock: 0.1
  max_position_total: 0.8

# 回测配置
backtest:
  commission_rate: 0.0005
  tax_rate: 0.001
  slippage: 0.002
  initial_capital: 1000000 